name: Yasmine Alani
favicon: null
layout_spectrum: 0.16338054719381034
typography_spectrum: 0.7300200196914375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.14302382781170309
  lightness: 0.8627971999812871
  saturation: 0.19657206744886935
  rhythmicContrast: 0.2812599977478385
purpose: []
